### ISSUE TITLE
Cannot view template documents

### ISSUE THREAD

**Issue by JavaDevilNZ** [Docmosis/tornado-docker#10]
Once you get the docker image built and up and running, you cannot view templates in the browser. 

The following line is logged:

2023-07-21 05:18:16,085 [http-nio-8080-exec-2] WARNING com.docmosis.webserver.server.ConfigurationServiceImpl - Unable to launch template viewer, desktop not supported

**Comment by mikehhodgson** [comment]
Opening the template is not supported when running Tornado in a container.

In this situation, Tornado should be behaving as if it were a remote server and offer the template for download.

I have forwarded this issue to the Tornado dev team for review.
