### ISSUE TITLE
Unknown argument "localinstall" for command "dnf5"

### ISSUE THREAD

**Issue by taylor-gridunity** [Docmosis/tornado-docker#16]
In the last few days, the Docker image build suddenly started failing with an error of `Unknown argument "localinstall" for command "dnf5"`. This is actually the line `yum localinstall -y --setopt=tsflags=nodocs *.rpm`. It seems that `localinstall` was deprecated and then removed from dnf5 (the Fedora version of yum), but it is replaced with simply `install`.

In my local testing, replacing it with `yum install -y --setopt=tsflags=nodocs *.rpm` resolves the issue.

**Comment by ww-tsy** [comment]
I had the same issue and the suggested change fixed it. Thanks!
