### ISSUE TITLE
epel-release-latest-7 not found

### ISSUE THREAD

**Issue by ironbirdie** [Docmosis/tornado-docker#2]
Hi,

Interesting project, I'm currently looking for a way to deploy tornado and using docker seems like a good idea.
I tried to run the docker-file, but i get following error.

#4 0.398 Loaded plugins: fastestmirror, ovl
#4 0.896 Cannot open: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm. Skipping.
#4 0.896 Error: Nothing to do

Should ik replace this epel-release by a newer version ?
And would it be recommended to upgrade to LibreOffice 7 and docmosis 4.6.1 ?

Kind regards,

Bart

**Comment by mikehhodgson** [comment]
Hi Bart,

That URL is currently working for me, and the docker build is currently working too. Perhaps this was a temporary or localized outage?

The epel-release version should match the current OS version - CentOS 7. This is required to install cabextract, which is a dependency of the mscorefonts2 package.

If you were creating your own Dockerfile based on this example, and did not require the mscorefonts2 installation, then the epel should not be required. However, we recommend the mscorefonts2 package as it installs several commonly used fonts.

Our currently recommended version of LibreOffice is still 6.2.8.2, however this is likely to be updated in the future.

We have now updated this image to the latest Tornado 2.8.3.
