### ISSUE TITLE
Docker build hanging on msttcore fonts install

### ISSUE THREAD

**Issue by bladepoint6969** [Docmosis/tornado-docker#3]
The docker build is hanging when it gets to the stage where it downloads and installs `msttcore-fonts-installer-2.6-1.noarch.rpm`

Following the build steps manually in a centos:7 container and cancelling at that install prints the following to the console:
```
### Using tmp directory /tmp/refresh-msttcore-fonts-A6QuRq
### Downloading andale32.exe from http://downloads.sourceforge.net/corefonts
ERROR: cannot verify pilotfiber.dl.sourceforge.net's certificate, issued by '/C=US/O=Let\'s Encrypt/CN=R3':
  Issued certificate has expired.
To connect to pilotfiber.dl.sourceforge.net insecurely, use `--no-check-certificate'.
Error: andale32.exe does not exist
Error: failed to download http://downloads.sourceforge.net/corefonts/andale32.exe: attempt 1
### Downloading andale32.exe from http://downloads.sourceforge.net/corefonts
ERROR: cannot verify newcontinuum.dl.sourceforge.net's certificate, issued by '/C=US/O=Let\'s Encrypt/CN=R3':
  Issued certificate has expired.
To connect to newcontinuum.dl.sourceforge.net insecurely, use `--no-check-certificate'.
Error: andale32.exe does not exist
...
```

Possibly related to the recent expiration of Let's Encrypt's Root CA?

**Comment by mikehhodgson** [comment]
Thanks Ben! With 17f198654686fbd959d5978b0245adebb31fd630 we've updated the Dockerfile to now use CentOS 8. Are you able to confirm this resolves the build issue for you please?

**Comment by placaze** [comment]
According to this article https://blog.devgenius.io/rhel-centos-7-fix-for-lets-encrypt-change-8af2de587fe4, the `ca-certificates` package was updated on 23/09/2021 (version *2021.2.50–72*) to fix this.

It's also available for CentOS 7 : http://mirror.centos.org/centos/7/updates/x86_64/Packages/ca-certificates-2021.2.50-72.el7_9.noarch.rpm

I didn't try it but I think a `yum update` can fix this.

Dockerfile for CentOS 7 :
```
RUN yum update \
    && yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm \
    && rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7 \
    && [...]
```

Dockerfile for CentOS 8 :
```
RUN yum update \
    && yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm \
    && rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-8 \
    && [...]
```

**Comment by placaze** [comment]
@mikehhodgson Just one thing: CentOS 8 is "end of life" on 31/12/2021 (https://en.wikipedia.org/wiki/CentOS#End-of-support_schedule). CentOS 7 is maintained until 30/06/2024. I don't know if moving to CentOS 8 is the best move. Maybe try [Rocky Linux](https://rockylinux.org/)?

**Comment by bladepoint6969** [comment]
Adding the `yum update -y` to the first `RUN` as @placaze suggested allowed me to get past that step, and build an image.

I've attached my updated Dockerfile to this comment (with a `.txt` extension so Github allows the extension). Unrelated, but I also removed the `--quiet` option on the LibreOffice `wget` because it takes quite a long time to download and I wanted to be sure it was progressing. Keep or remove that change as desired.

[Dockerfile.txt](https://github.com/Docmosis/tornado-docker/files/7280034/Dockerfile.txt)
.

**Comment by bladepoint6969** [comment]
I've created a PR with the necessary changes.

**Comment by mikehhodgson** [comment]
Thanks @bladepoint6969 and @placaze. Excellent point regarding CentOS 8.

We did try the yum update solution first, however after doing so we found it was reliably breaking the EPEL installation with a TLS handshake failure at that time.

I can no longer replicate that behaviour, so perhaps a transient issue and happy to revert.
